version: "3.8"

services:
  oracle-db:
    image: my-oracle-db:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    environment:
      - ORACLE_PWD=admin # Senha para o usuário SYS, SYSTEM e PDBADMIN
      - ORACLE_SID=ORCL
    networks:
      - app-network

  java-app:
    image: my-java-app:latest
    container_name: java-app
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/ORCL
      - SPRING_DATASOURCE_USERNAME=RM555962
      - SPRING_DATASOURCE_PASSWORD=191105
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - app-network

volumes:
  oracle_data:

networks:
  app-network:
    driver: bridge
